{% set name = "torch_geometric" %}
{% set version = "2.4.0" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/pyg-team/pytorch_geometric.git
  git_rev: {{ version }}

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  noarch: python

requirements:
  host:
    - pip
    - pytest-runner
    - python
    - setuptools {{ setuptools }}
    - flit-core
  run:
    - googledrivedownloader  {{ googledrivedownloader }}
    - jinja2
    - networkx
    - numpy {{ numpy }}
    - pandas
    - pyparsing
    - python
    - python-louvain
    - requests {{ requests }}
    - rdflib {{ rdflib }}
    - scikit-learn {{ scikit_learn }}
    - scipy {{ scipy }}
    - tqdm  {{tqdm }}
    - pytorch-base {{ pytorch }}
    - pytorch_sparse  {{ pytorch_sparse }}
    - yacs
    - psutil {{ psutil }}

test:
  imports:
    - torch_sparse
    - torch_geometric
    - torch_geometric.nn
    - torch_geometric.data
    - torch_geometric.utils
    - torch_geometric.datasets
    - torch_geometric.transforms
  commands:
    - pip check
about:
  home: https://github.com/pyg-team/pytorch_geometric
  summary: Geometric Deep Learning Extension Library for PyTorch
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pyg-team/pytorch_geometric

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
