{% set name = "torch_geometric" %}
{% set version = "2.1.0" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/pyg-team/pytorch_geometric.git
  git_rev: {{ version }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - pytest-runner
    - python
    - setuptools {{ setuptools }}
  run:
    - googledrivedownloader  {{ googledrivedownloader }}
    - jinja2
    - networkx  {{ networkx }}
    - numpy {{ numpy }}
    - pandas
    - pyparsing
    - python
    - python-louvain
    - requests {{ requests }}
    - rdflib {{ rdflib }}
    - scikit-learn
    - scipy {{ scipy }}
    - tqdm  {{tqdm }}
    - pytorch-base {{ pytorch }}
    - pytorch_sparse  {{ pytorch_sparse }}
    - yacs
test:
  imports:
    - torch_geometric
  commands:
    - pip check
about:
  home: https://github.com/rusty1s/pytorch_geometric
  summary: Geometric Deep Learning Extension Library for PyTorch
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_geometric

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
